### ISSUE TITLE
Checking only stdout is fallible

### ISSUE THREAD

**Issue by cole-miller** [eminence/terminal-size#23]
Say I have a program that writes its output to stderr, and I use it in a pipeline like

```
cat whatever.txt | myprogram | grep 'foo'
```

Then `terminal_size` will return `None` because stdout is not a tty, even though stderr is, and I can't use it to format the program's output.

I can think of a few solutions:

- check stderr instead of stdout by default (this seems reasonable since human-oriented output is the main use case for getting the terminal size)
- add another function that checks stderr
- whatever the cross-platform equivalent is of opening `/dev/tty` (is there one?)

[Here](https://github.com/fosskers/linya/pull/1) is the thread that prompted me to open this. Thanks for your work on this crate!

**Comment by cole-miller** [comment]
Ah, I see there are platform-specific functions that take a file descriptor or handle. But checking stderr is a portable strategy, so I think it'd be worth adding a function that does that.

**Comment by eminence** [comment]
I think you're right, there's a good argument to be made for a portable function that'll check stderr
