### ISSUE TITLE
Error compiling terminal_size in mac

### ISSUE THREAD

**Issue by ivanceras** [eminence/terminal-size#3]
.multirust/toolchains/stable/cargo/registry/src/github.com-88ac128001ac3a9a/terminal_size-0.1.1/src/unix.rs:28:29: 28:39 error: mismatched types:
 expected `u64`,
    found `i32`
(expected u64,
    found i32) [E0308]
.multirust/toolchains/stable/cargo/registry/src/github.com-88ac128001ac3a9a/terminal_size-0.1.1/src/unix.rs:28         ioctl(STDIN_FILENO, TIOCGWINSZ, &mut winsize);

**Comment by andersfischernielsen** [comment]
I have the same issue. 

	/Users/Anders/.cargo/registry/src/github.com-0a35038f75765ae4/terminal_size-0.1.1/src/unix.rs:28:29: 28:39 error: mismatched types:
	 expected `u64`,
	    found `i32`
	(expected u64,
	    found i32) [E0308]
	/Users/Anders/.cargo/registry/src/github.com-0a35038f75765ae4/terminal_size-0.1.1/src/unix.rs:28         ioctl(STDIN_FILENO, TIOCGWINSZ, &mut winsize);
	                                                                                                                             ^~~~~~~~~~
	/Users/Anders/.cargo/registry/src/github.com-0a35038f75765ae4/terminal_size-0.1.1/src/unix.rs:28:29: 28:39 help: run `rustc --explain E0308` to see a detailed explanation
	error: aborting due to previous error
	Build failed, waiting for other jobs to finish...
	Could not compile `terminal_size`.

**Comment by eminence** [comment]
Thanks for the report!  I've pushed a fix for this, and published it to crates.io as version 0.1.4 (was previously 0.1.3)

**Comment by eminence** [comment]
CC https://github.com/hopey-dishwasher/termpix/pull/3
