### ISSUE TITLE
Observer over terminal-size values

### ISSUE THREAD

**Issue by deg0nz** [eminence/terminal-size#30]
Hi,

this issue is related to [this comment](https://github.com/mitsuhiko/dialoguer/pull/130#issuecomment-912372349) in mitsuhiko/dialoguer#130.

We were trying to re-render prompts on resize of the terminal and I wasn't sure how to implement this. So I wanted to ask if someone here has an idea, how we can raise some kind of event when the terminal size changes.

My idea was to create a busy `loop` over these values and raise an event if some value has changed. But I have absolutely no idea how much load that would create while querying unix file descriptors or the `winapi` respectively. I have no experience with these kind of things.

Or maybe you have an idea for a completely different approach.

I'm definitely willing to make a PR to make this happen, but I wanted to clarify this stuff first.

I hope, someone can help :)

Best regards
Beh

**Comment by eminence** [comment]
Hi there, sorry for not replying sooner.  Constantly pooling for terminal size changes is not something that `terminal-size` should do.  On Linux, you can listen for the `WINCH` signal to know when the terminal size changes.  I bet Windows has some callback you can register, but I don't know it off-hand.

The [tui](https://crates.io/crates/tui) crate can also send events when the terminal size changes, so looking at how tui does it might be useful too.

Good luck!
