### ISSUE TITLE
problems with stdout

### ISSUE THREAD

**Issue by fdncred** [eminence/terminal-size#48]
we have a plugin that is already communicating on stdout. for some reason, when terminal-size tries to open stdout again and call getconsolescreenbufferinfo, it fails. It would be nice to do something kind of similar to term-size where they check all 3 like this, instead of just silently failing.
```rust
    if unsafe { GetConsoleScreenBufferInfo(GetStdHandle(STD_OUTPUT_HANDLE), &mut console_data) } != 0 ||
        unsafe { GetConsoleScreenBufferInfo(GetStdHandle(STD_INPUT_HANDLE), &mut console_data) } != 0 ||
        unsafe { GetConsoleScreenBufferInfo(GetStdHandle(STD_ERROR_HANDLE), &mut console_data) } != 0 {
        Some(((console_data.srWindow.Right - console_data.srWindow.Left + 1) as usize,
                (console_data.srWindow.Bottom - console_data.srWindow.Top + 1) as usize))
    } else {
        None
    }
```

**Comment by eminence** [comment]
Thanks for the report.  I think you have the right idea here.   We should be checking all 3 streams, and using the size from the first one that doesn't return an error.
