### ISSUE TITLE
Fallback to STDERR and /dev/tty

### ISSUE THREAD

**Issue by stbuehler** [eminence/terminal-size#8]
Hi,

it would be nice if the terminal detection would also try STDERR and open(/dev/tty) if STDOUT is not a terminal.

My usecase is a tool using https://github.com/a8m/pb and for which I'd like to be able to redirect the (stdout) output into a file.

**Comment by aep** [comment]
@stbuehler how did you end up implementing it? (pb is amazing btw <3)

**Comment by stbuehler** [comment]
@aep I stopped using STDOUT (for this specific tool); had to produce multiple files anyway.

**Comment by TimDeve** [comment]
#12

**Comment by stbuehler** [comment]
I guess #12 solves this or at least moves the problem to `pb`.
