### ISSUE TITLE
Move to winapi 0.3

### ISSUE THREAD

**Issue by Lokathor** [eminence/terminal-size#9]
With the new 0.3 branch of `winapi`, compile times are much smaller because it only builds the bindings for the portions of winapi actually used in a build. Since this crate uses only a few functions all from the same module, it would be a great benefit to move to the 0.3 series of winapi.

**Comment by eminence** [comment]
Nice!  Updating from 0.2 to 0.3 reduced the build times from about 25 seconds to 5 seconds!     I've just published `terminal-size` version v0.1.8 that depends on winapi 0.3
